export default [
    // {
    //     id: '1292742131685634050',
    //     parentId: '-1',
    //     clientId: 'sino-jh',
    //     code: '123',
    //     name: '经销商管理',
    //     alias: 'menu',
    //     path: '/factory-customermanage/index',
    //     source: 'tianshenpi',
    //     sort: 105,
    //     category: 1,
    //     action: 0,
    //     isOpen: 1,
    //     remark: '',
    //     isDeleted: 0,
    //     children: [
    //     ],
    //     hasChildren: false,
    //     parentName: '',
    //     categoryName: '',
    //     actionName: '',
    //     isOpenName: ''
    // },
    {
        id: '1292741631359692802',
        parentId: '-1',
        clientId: 'sino-jh',
        code: 'my',
        name: '产品管理',
        alias: 'menu',
        path: '/factory-goods/goods-index',
        source: 'yingjian',
        sort: 103,
        category: 1,
        action: 0,
        isOpen: 1,
        remark: '',
        isDeleted: 0,
        children: [
        ],
        hasChildren: false,
        parentName: '',
        categoryName: '',
        actionName: '',
        isOpenName: ''
    },
    {
        id: '1292741631359692812',
        parentId: '-1',
        clientId: 'sino-jh',
        code: 'my',
        name: '经销商管理',
        alias: 'menu',
        path: '/dealer-manager/index',
        source: 'yibiaopan',
        sort: 103,
        category: 1,
        action: 0,
        isOpen: 1,
        remark: '',
        isDeleted: 0,
        children: [
        ],
        hasChildren: false,
        parentName: '',
        categoryName: '',
        actionName: '',
        isOpenName: ''
    },
    {
        id: '1303944536058568706',
        parentId: '-1',
        clientId: 'sino-jh',
        code: 'healthy',
        name: '厂家活动',
        alias: 'healthy_user',
        path: '/activity/activity-index',
        source: 'menu',
        sort: 104,
        category: 1,
        action: 0,
        isOpen: 1,
        remark: '',
        isDeleted: 0,
        children: [
        ],
        hasChildren: false,
        parentName: '',
        categoryName: '',
        actionName: '',
        isOpenName: ''
    },
    {
        id: '1292742131685634051',
        parentId: '-1',
        clientId: 'sino-jh',
        code: '123',
        name: '订单管理',
        alias: 'menu',
        path: '/order/order-list',
        source: 'shoucang',
        sort: 106,
        category: 1,
        action: 0,
        isOpen: 1,
        remark: '',
        isDeleted: 0,
        children: [
        ],
        hasChildren: false,
        parentName: '',
        categoryName: '',
        actionName: '',
        isOpenName: ''
    },
    {
        id: '1292742131685634052',
        parentId: '-1',
        clientId: 'sino-jh',
        code: '123',
        name: '统计数据报表',
        alias: 'menu',
        path: '/report/report-index',
        source: 'fenzuguanli',
        sort: 106,
        category: 1,
        action: 0,
        isOpen: 1,
        remark: '',
        isDeleted: 0,
        children: [
        ],
        hasChildren: false,
        parentName: '',
        categoryName: '',
        actionName: '',
        isOpenName: ''
    },
    {
        id: '1292742131685634053',
        parentId: '-1',
        clientId: 'sino-jh',
        code: '123',
        name: '系统管理',
        alias: 'menu',
        path: '/',
        source: 'shezhi',
        sort: 106,
        category: 1,
        action: 0,
        isOpen: 1,
        remark: '',
        isDeleted: 0,
        children: [
        ],
        hasChildren: false,
        parentName: '',
        categoryName: '',
        actionName: '',
        isOpenName: ''
    }
]
