export default [
    // {
    //     id: '1292738436260540418',
    //     parentId: '-1',
    //     clientId: 'sino-jh',
    //     code: 'online_medical',
    //     name: '运营首页',
    //     alias: 'menu',
    //     path: '/home',
    //     source: 'customer',
    //     sort: 102,
    //     category: 1,
    //     action: 0,
    //     isOpen: 1,
    //     remark: '',
    //     isDeleted: 0,
    //     children: [
    //     ],
    //     hasChildren: false,
    //     parentName: '',
    //     categoryName: '',
    //     actionName: '',
    //     isOpenName: ''
    // },
    {
        id: '1292741333094346753',
        parentId: '-1',
        clientId: 'sino-jh',
        code: 'jl',
        name: '店铺管理',
        alias: 'menu',
        path: '/shop/shop-index',
        source: 'zidingyi',
        sort: 103,
        category: 1,
        action: 0,
        isOpen: 1,
        remark: '',
        isDeleted: 0,
        children: [
        ],
        hasChildren: false,
        parentName: '',
        categoryName: '',
        actionName: '',
        isOpenName: ''
    },
    {
        id: '1292741631359692802',
        parentId: '-1',
        clientId: 'sino-jh',
        code: 'my',
        name: '产品管理',
        alias: 'menu',
        path: '/goods/goods-index',
        source: 'yingjian',
        sort: 103,
        category: 1,
        action: 0,
        isOpen: 1,
        remark: '',
        isDeleted: 0,
        children: [
        ],
        hasChildren: false,
        parentName: '',
        categoryName: '',
        actionName: '',
        isOpenName: ''
    },
    {
        id: '1292742131685634050',
        parentId: '-1',
        clientId: 'sino-jh',
        code: '123',
        name: '客户管理',
        alias: 'menu',
        path: '/customermanage/index',
        source: 'tianshenpi',
        sort: 105,
        category: 1,
        action: 0,
        isOpen: 1,
        remark: '',
        isDeleted: 0,
        children: [
        ],
        hasChildren: false,
        parentName: '',
        categoryName: '',
        actionName: '',
        isOpenName: ''
    },
    {
        id: '1292742131685634051',
        parentId: '-1',
        clientId: 'sino-jh',
        code: '123',
        name: '订单管理',
        alias: 'menu',
        path: '/order/order-list',
        source: 'shoucang',
        sort: 106,
        category: 1,
        action: 0,
        isOpen: 1,
        remark: '',
        isDeleted: 0,
        children: [
        ],
        hasChildren: false,
        parentName: '',
        categoryName: '',
        actionName: '',
        isOpenName: ''
    },
    {
        id: '1292742131685634052',
        parentId: '-1',
        clientId: 'sino-jh',
        code: '123',
        name: '价格管理',
        alias: 'menu',
        path: '/price/price-index',
        source: 'yingyongguanli1',
        sort: 106,
        category: 1,
        action: 0,
        isOpen: 1,
        remark: '',
        isDeleted: 0,
        children: [
        ],
        hasChildren: false,
        parentName: '',
        categoryName: '',
        actionName: '',
        isOpenName: ''
    },

    {
        id: '1303944536058568706',
        parentId: '-1',
        clientId: 'sino-jh',
        code: 'healthy',
        name: '活动管理',
        alias: 'healthy_user',
        path: '/activity/activity-index',
        source: 'menu',
        sort: 104,
        category: 1,
        action: 0,
        isOpen: 1,
        remark: '',
        isDeleted: 0,
        children: [
        ],
        hasChildren: false,
        parentName: '',
        categoryName: '',
        actionName: '',
        isOpenName: ''
    }
    //,
    // {
    //     id: '1292742131685634053',
    //     parentId: '-1',
    //     clientId: 'sino-jh',
    //     code: '123',
    //     name: '系统管理',
    //     alias: 'menu',
    //     path: '/',
    //     source: 'shezhi',
    //     sort: 106,
    //     category: 1,
    //     action: 0,
    //     isOpen: 1,
    //     remark: '',
    //     isDeleted: 0,
    //     children: [
    //     ],
    //     hasChildren: false,
    //     parentName: '',
    //     categoryName: '',
    //     actionName: '',
    //     isOpenName: ''
    // }
]
